default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>
  pool: 5

development:
  <<: *default
  database: reactive_checkout_development

test:
  <<: *default
  database: reactive_checkout_test

production:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['DB_PORT']%>
  host: <%= ENV['DB_HOST']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>
  pool: 5
