default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  username: 'postgres'
  password: ''
  pool: 5

development:
  <<: *default
  database: reactive_checkout_development

test:
  <<: *default
  database: reactive_checkout_test
